<?php
namespace AstraxAddons\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Canonical metadata for all 405 Astrax widgets.
 * Auto-generated by scaffold-widgets.sh — safe to re-run.
 */
class WidgetRegistry {
	/**
	 * @return array<string, array{name: string, class: string, file: string}>
	 */
	public static function all() {
		return array_merge(
			// --- Root-level (no sub-folder) ---
			self::definitions( '', [
				'advanced-heading'    => [ 'Advanced Heading',    'AdvancedHeading'    ],
				'advanced-button'     => [ 'Advanced Button',     'AdvancedButton'     ],
				'icon-box'            => [ 'Icon Box',            'IconBox'            ],
				'info-box'            => [ 'Info Box',            'InfoBox'            ],
				'image-accordion'     => [ 'Image Accordion',     'ImageAccordion'     ],
				'post-grid'           => [ 'Post Grid',           'PostGrid'           ],
				'woo-product-grid'    => [ 'Woo Product Grid',    'WooProductGrid'     ],
				'woo-product-carousel'=> [ 'Woo Product Carousel','WooProductCarousel' ],
				'woo-category-grid'   => [ 'Woo Category Grid',   'WooCategoryGrid'    ],
			] ),

			// --- Content ---
			self::definitions( 'Content', [
				'heading'        => [ 'Heading',              'Heading'       ],
				'text-editor'    => [ 'Text Editor',          'TextEditor'    ],
				'rich-text'      => [ 'Rich Text',            'RichText'      ],
				'icon'           => [ 'Icon',                 'Icon'          ],
				'image'          => [ 'Image',                'Image'         ],
				'image-box'      => [ 'Image Box',            'ImageBox'      ],
				'image-text'     => [ 'Image + Text',         'ImageText'     ],
				'button'         => [ 'Button',               'Button'        ],
				'dual-button'    => [ 'Dual Button',          'DualButton'    ],
				'cta'            => [ 'Call to Action',       'CallToAction'  ],
				'badge'          => [ 'Badge',                'Badge'         ],
				'label'          => [ 'Label',                'Label'         ],
				'divider'        => [ 'Divider',              'Divider'       ],
				'spacer'         => [ 'Spacer',               'Spacer'        ],
				'notice'         => [ 'Notice',               'Notice'        ],
				'blockquote'     => [ 'Blockquote',           'Blockquote'    ],
				'drop-cap'       => [ 'Drop Cap',             'DropCap'       ],
				'highlight-text' => [ 'Highlight Text',       'HighlightText' ],
				'content-toggle' => [ 'Content Toggle',       'ContentToggle' ],
				'read-more'      => [ 'Read More / Read Less','ReadMore'      ],
			] ),

			// --- Images ---
			self::definitions( 'Images', [
				'gallery'              => [ 'Image Gallery',      'Gallery'            ],
				'masonry-gallery'      => [ 'Masonry Gallery',    'MasonryGallery'     ],
				'justified-gallery'    => [ 'Justified Gallery',  'JustifiedGallery'   ],
				'image-carousel'       => [ 'Image Carousel',     'ImageCarousel'      ],
				'image-slider'         => [ 'Image Slider',       'ImageSlider'        ],
				'before-after'         => [ 'Before/After Image', 'BeforeAfter'        ],
				'hotspots'             => [ 'Image Hotspots',     'Hotspots'           ],
				'image-stack'          => [ 'Image Stack',        'ImageStack'         ],
				'image-reveal'         => [ 'Image Reveal',       'ImageReveal'        ],
				'image-mask'           => [ 'Image Mask',         'ImageMask'          ],
				'image-hover-effects'  => [ 'Image Hover Effects','ImageHoverEffects'  ],
				'interactive-image'    => [ 'Interactive Image',  'InteractiveImage'   ],
				'floating-image'       => [ 'Floating Image',     'FloatingImage'      ],
				'scrolling-image'      => [ 'Scrolling Image',    'ScrollingImage'     ],
				'image-magnifier'      => [ 'Image Magnifier',    'ImageMagnifier'     ],
				'lightbox-gallery'     => [ 'Lightbox Gallery',   'LightboxGallery'    ],
			] ),

			// --- Typography ---
			self::definitions( 'Typography', [
				'animated-heading'      => [ 'Animated Heading',       'AnimatedHeading'      ],
				'text-marquee'          => [ 'Text Marquee',           'TextMarquee'          ],
				'text-rotator'          => [ 'Text Rotator',           'TextRotator'          ],
				'typing-text'           => [ 'Typing Text',            'TypingText'           ],
				'gradient-text'         => [ 'Gradient Text',          'GradientText'         ],
				'glitch-text'           => [ 'Glitch Text',            'GlitchText'           ],
				'stroke-text'           => [ 'Stroke Text',            'StrokeText'           ],
				'text-reveal'           => [ 'Text Reveal',            'TextReveal'           ],
				'text-split-animation'  => [ 'Text Split Animation',   'TextSplitAnimation'   ],
				'character-animation'   => [ 'Character Animation',    'CharacterAnimation'   ],
				'word-animation'        => [ 'Word Animation',         'WordAnimation'        ],
				'highlight-animation'   => [ 'Highlight Animation',    'HighlightAnimation'   ],
				'counter'               => [ 'Counter',                'Counter'              ],
				'dynamic-text'          => [ 'Dynamic Text',           'DynamicText'          ],
			] ),

			// --- Navigation ---
			self::definitions( 'Navigation', [
				'advanced-menu'  => [ 'Advanced Menu',       'AdvancedMenu'   ],
				'mega-menu'      => [ 'Mega Menu',           'MegaMenu'       ],
				'off-canvas-menu'=> [ 'Off-Canvas Menu',     'OffCanvasMenu'  ],
				'hamburger-menu' => [ 'Hamburger Menu',      'HamburgerMenu'  ],
				'mobile-menu'    => [ 'Mobile Menu',         'MobileMenu'     ],
				'breadcrumbs'    => [ 'Breadcrumbs',         'Breadcrumbs'    ],
				'page-navigation'=> [ 'Page Navigation',     'PageNavigation' ],
				'pagination'     => [ 'Pagination',          'Pagination'     ],
				'toc'            => [ 'Table of Contents',   'TableOfContents'],
				'sticky-nav'     => [ 'Sticky Navigation',   'StickyNav'      ],
				'vertical-nav'   => [ 'Vertical Navigation', 'VerticalNav'    ],
				'one-page-nav'   => [ 'One Page Navigation', 'OnePageNav'     ],
				'category-menu'  => [ 'Category Menu',       'CategoryMenu'   ],
				'filter-nav'     => [ 'Filter Navigation',   'FilterNav'      ],
			] ),

			// --- Blog / Posts ---
			self::definitions( 'Blog', [
				'post-list'           => [ 'Post List',           'PostList'          ],
				'post-carousel'       => [ 'Post Carousel',       'PostCarousel'      ],
				'post-slider'         => [ 'Post Slider',         'PostSlider'        ],
				'post-masonry'        => [ 'Post Masonry',        'PostMasonry'       ],
				'post-timeline'       => [ 'Post Timeline',       'PostTimeline'      ],
				'featured-posts'      => [ 'Featured Posts',      'FeaturedPosts'     ],
				'recent-posts'        => [ 'Recent Posts',        'RecentPosts'       ],
				'related-posts'       => [ 'Related Posts',       'RelatedPosts'      ],
				'popular-posts'       => [ 'Popular Posts',       'PopularPosts'      ],
				'author-box'          => [ 'Author Box',          'AuthorBox'         ],
				'post-meta'           => [ 'Post Meta',           'PostMeta'          ],
				'post-title'          => [ 'Post Title',          'PostTitle'         ],
				'post-excerpt'        => [ 'Post Excerpt',        'PostExcerpt'       ],
				'post-content'        => [ 'Post Content',        'PostContent'       ],
				'post-featured-image' => [ 'Post Featured Image', 'PostFeaturedImage' ],
				'post-navigation'     => [ 'Post Navigation',     'PostNavigation'    ],
				'comments'            => [ 'Comments',            'Comments'          ],
				'comment-form'        => [ 'Comment Form',        'CommentForm'       ],
				'archive-posts'       => [ 'Archive Posts',       'ArchivePosts'      ],
				'category-posts'      => [ 'Category Posts',      'CategoryPosts'     ],
				'tag-posts'           => [ 'Tag Posts',           'TagPosts'          ],
				'search-results'      => [ 'Search Results',      'SearchResults'     ],
				'load-more-posts'     => [ 'Load More Posts',     'LoadMorePosts'     ],
				'ajax-posts'          => [ 'AJAX Posts',          'AjaxPosts'         ],
				'infinite-scroll'     => [ 'Infinite Scroll',     'InfiniteScroll'    ],
			] ),

			// --- Team ---
			self::definitions( 'Team', [
				'team-card'        => [ 'Team Member Card', 'TeamCard'        ],
				'team-member'      => [ 'Team Member',      'TeamMember'      ],
				'team-grid'        => [ 'Team Grid',        'TeamGrid'        ],
				'team-carousel'    => [ 'Team Carousel',    'TeamCarousel'    ],
				'team-slider'      => [ 'Team Slider',      'TeamSlider'      ],
				'team-masonry'     => [ 'Team Masonry',     'TeamMasonry'     ],
				'team-timeline'    => [ 'Team Timeline',    'TeamTimeline'    ],
				'team-social-links'=> [ 'Team Social Links','TeamSocialLinks' ],
				'team-filter'      => [ 'Team Filter',      'TeamFilter'      ],
				'staff-directory'  => [ 'Staff Directory',  'StaffDirectory'  ],
				'employee-profile' => [ 'Employee Profile', 'EmployeeProfile' ],
			] ),

			// --- Testimonials ---
			self::definitions( 'Testimonials', [
				'testimonial'         => [ 'Testimonial',         'Testimonial'        ],
				'testimonial-slider'  => [ 'Testimonial Slider',  'TestimonialSlider'  ],
				'testimonial-carousel'=> [ 'Testimonial Carousel','TestimonialCarousel'],
				'testimonial-grid'    => [ 'Testimonial Grid',    'TestimonialGrid'    ],
				'testimonial-masonry' => [ 'Testimonial Masonry', 'TestimonialMasonry' ],
				'testimonial-cards'   => [ 'Testimonial Cards',   'TestimonialCards'   ],
				'review-slider'       => [ 'Review Slider',       'ReviewSlider'       ],
				'customer-reviews'    => [ 'Customer Reviews',    'CustomerReviews'    ],
				'rating'              => [ 'Rating',              'Rating'             ],
				'star-rating'         => [ 'Star Rating',         'StarRating'         ],
				'review-carousel'     => [ 'Review Carousel',     'ReviewCarousel'     ],
				'video-testimonials'  => [ 'Video Testimonials',  'VideoTestimonials'  ],
			] ),

			// --- Social Media ---
			self::definitions( 'Social', [
				'social-facebook' => [ 'Facebook',       'Facebook'      ],
				'social-instagram'=> [ 'Instagram',      'Instagram'     ],
				'social-twitter'  => [ 'X / Twitter',    'Twitter'       ],
				'social-youtube'  => [ 'YouTube',        'YouTube'       ],
				'social-tiktok'   => [ 'TikTok',         'TikTok'        ],
				'social-pinterest'=> [ 'Pinterest',      'Pinterest'     ],
				'social-linkedin' => [ 'LinkedIn',       'LinkedIn'      ],
				'social-icons'    => [ 'Social Icons',   'SocialIcons'   ],
				'social-share'    => [ 'Social Share',   'SocialShare'   ],
				'social-follow'   => [ 'Social Follow',  'SocialFollow'  ],
				'social-counter'  => [ 'Social Counter', 'SocialCounter' ],
				'social-profile'  => [ 'Social Profile', 'SocialProfile' ],
				'social-posts'    => [ 'Social Posts',   'SocialPosts'   ],
			] ),

			// --- WooCommerce ---
			self::definitions( 'Woo', [
				'woo-product-list'       => [ 'Product List',          'ProductList'       ],
				'woo-product-slider'     => [ 'Product Slider',        'ProductSlider'     ],
				'woo-product-search'     => [ 'Product Search',        'ProductSearch'     ],
				'woo-product-filters'    => [ 'Product Filters',       'ProductFilters'    ],
				'woo-ajax-filters'       => [ 'AJAX Product Filters',  'AjaxFilters'       ],
				'woo-product-rating'     => [ 'Product Rating',        'ProductRating'     ],
				'woo-product-price'      => [ 'Product Price',         'ProductPrice'      ],
				'woo-product-image'      => [ 'Product Image',         'ProductImage'      ],
				'woo-add-to-cart'        => [ 'Add to Cart',           'AddToCart'         ],
				'woo-buy-now'            => [ 'Buy Now',               'BuyNow'            ],
				'woo-product-badge'      => [ 'Product Badge',         'ProductBadge'      ],
				'woo-product-meta'       => [ 'Product Meta',          'ProductMeta'       ],
				'woo-product-tabs'       => [ 'Product Tabs',          'ProductTabs'       ],
				'woo-product-accordion'  => [ 'Product Accordion',     'ProductAccordion'  ],
				'woo-product-gallery'    => [ 'Product Gallery',       'ProductGallery'    ],
				'woo-product-variations' => [ 'Product Variations',    'ProductVariations' ],
				'woo-product-comparison' => [ 'Product Comparison',    'ProductComparison' ],
				'woo-wishlist'           => [ 'Wishlist',              'Wishlist'          ],
				'woo-mini-cart'          => [ 'Mini Cart',             'MiniCart'          ],
				'woo-cart'               => [ 'Cart',                  'Cart'              ],
				'woo-checkout'           => [ 'Checkout',              'Checkout'          ],
				'woo-my-account'         => [ 'My Account',            'MyAccount'         ],
				'woo-order-tracking'     => [ 'Order Tracking',        'OrderTracking'     ],
				'woo-related-products'   => [ 'Related Products',      'RelatedProducts'   ],
				'woo-upsells'            => [ 'Upsells',               'Upsells'           ],
				'woo-cross-sells'        => [ 'Cross-sells',           'CrossSells'        ],
				'woo-recently-viewed'    => [ 'Recently Viewed',       'RecentlyViewed'    ],
				'woo-flash-sale'         => [ 'Flash Sale',            'FlashSale'         ],
				'woo-sale-products'      => [ 'Sale Products',         'SaleProducts'      ],
				'woo-best-selling'       => [ 'Best Selling Products', 'BestSelling'       ],
				'woo-featured-products'  => [ 'Featured Products',     'FeaturedProducts'  ],
			] ),

			// --- Forms ---
			self::definitions( 'Forms', [
				'contact-form'       => [ 'Contact Form',      'ContactForm'      ],
				'multi-step-form'    => [ 'Multi-Step Form',   'MultiStepForm'    ],
				'login-form'         => [ 'Login Form',        'LoginForm'        ],
				'registration-form'  => [ 'Registration Form', 'RegistrationForm' ],
				'newsletter-form'    => [ 'Newsletter Form',   'NewsletterForm'   ],
				'search-form'        => [ 'Search Form',       'SearchForm'       ],
				'quote-form'         => [ 'Quote Form',        'QuoteForm'        ],
				'booking-form'       => [ 'Booking Form',      'BookingForm'      ],
				'application-form'   => [ 'Application Form',  'ApplicationForm'  ],
				'feedback-form'      => [ 'Feedback Form',     'FeedbackForm'     ],
				'survey-form'        => [ 'Survey Form',       'SurveyForm'       ],
				'popup-form'         => [ 'Popup Form',        'PopupForm'        ],
				'ajax-form'          => [ 'AJAX Form',         'AjaxForm'         ],
				'file-upload-form'   => [ 'File Upload Form',  'FileUploadForm'   ],
				'conditional-form'   => [ 'Conditional Form',  'ConditionalForm'  ],
				'otp-form'           => [ 'OTP Form',          'OtpForm'          ],
				'password-reset-form'=> [ 'Password Reset Form','PasswordResetForm'],
			] ),

			// --- Business ---
			self::definitions( 'Business', [
				'pricing-table'     => [ 'Pricing Table',      'PricingTable'     ],
				'business-hours'    => [ 'Business Hours',     'BusinessHours'    ],
				'contact-info'      => [ 'Contact Information','ContactInfo'      ],
				'address'           => [ 'Address',            'Address'          ],
				'phone'             => [ 'Phone',              'Phone'            ],
				'email-widget'      => [ 'Email',              'Email'            ],
				'openstreet-map'    => [ 'OpenStreetMap',      'OpenStreetMap'    ],
				'store-locator'     => [ 'Store Locator',      'StoreLocator'     ],
				'opening-hours'     => [ 'Opening Hours',      'OpeningHours'     ],
				'pricing-toggle'    => [ 'Pricing Toggle',     'PricingToggle'    ],
				'services'          => [ 'Services',           'Services'         ],
				'service-grid'      => [ 'Service Grid',       'ServiceGrid'      ],
				'service-carousel'  => [ 'Service Carousel',   'ServiceCarousel'  ],
				'process-steps'     => [ 'Process Steps',      'ProcessSteps'     ],
				'features'          => [ 'Features',           'Features'         ],
				'feature-comparison'=> [ 'Feature Comparison', 'FeatureComparison'],
				'business-timeline' => [ 'Business Timeline',  'BusinessTimeline' ],
				'statistics'        => [ 'Statistics',         'Statistics'       ],
				'business-counter'  => [ 'Counter',            'Counter'          ],
				'progress-bar'      => [ 'Progress Bar',       'ProgressBar'      ],
			] ),

			// --- Marketing ---
			self::definitions( 'Marketing', [
				'marketing-cta'           => [ 'CTA',                    'Cta'             ],
				'countdown'               => [ 'Countdown',              'Countdown'       ],
				'sales-countdown'         => [ 'Sales Countdown',        'SalesCountdown'  ],
				'promo-banner'            => [ 'Promo Banner',           'PromoBanner'     ],
				'announcement-bar'        => [ 'Announcement Bar',       'AnnouncementBar' ],
				'coupon'                  => [ 'Coupon',                 'Coupon'          ],
				'coupon-reveal'           => [ 'Coupon Reveal',          'CouponReveal'    ],
				'marketing-pricing-table' => [ 'Pricing Table',          'PricingTable'    ],
				'marketing-pricing-toggle'=> [ 'Pricing Toggle',         'PricingToggle'   ],
				'comparison-table'        => [ 'Comparison Table',       'ComparisonTable' ],
				'feature-list'            => [ 'Feature List',           'FeatureList'     ],
				'trust-badges'            => [ 'Trust Badges',           'TrustBadges'     ],
				'logo-carousel'           => [ 'Logo Carousel',          'LogoCarousel'    ],
				'client-logos'            => [ 'Client Logos',           'ClientLogos'     ],
				'partner-logos'           => [ 'Partner Logos',          'PartnerLogos'    ],
				'newsletter'              => [ 'Newsletter',             'Newsletter'      ],
				'lead-capture'            => [ 'Lead Capture',           'LeadCapture'     ],
				'floating-cta'            => [ 'Floating CTA',           'FloatingCta'     ],
				'sticky-cta'              => [ 'Sticky CTA',             'StickyCta'       ],
			] ),

			// --- Animation ---
			self::definitions( 'Animation', [
				'lottie'            => [ 'Lottie Animation',    'Lottie'             ],
				'scroll-animation'  => [ 'Scroll Animation',    'ScrollAnimation'    ],
				'parallax'          => [ 'Parallax',            'Parallax'           ],
				'mouse-parallax'    => [ 'Mouse Parallax',      'MouseParallax'      ],
				'tilt-3d'           => [ '3D Tilt',             'Tilt3D'             ],
				'hover-animation'   => [ 'Hover Animation',     'HoverAnimation'     ],
				'magnetic-button'   => [ 'Magnetic Button',     'MagneticButton'     ],
				'cursor-effects'    => [ 'Cursor Effects',      'CursorEffects'      ],
				'custom-cursor'     => [ 'Custom Cursor',       'CustomCursor'       ],
				'anim-text-reveal'  => [ 'Text Reveal',         'TextReveal'         ],
				'anim-image-reveal' => [ 'Image Reveal',        'ImageReveal'        ],
				'scroll-progress'   => [ 'Scroll Progress',     'ScrollProgress'     ],
				'page-progress'     => [ 'Page Progress',       'PageProgress'       ],
				'anim-marquee'      => [ 'Marquee',             'Marquee'            ],
				'infinite-slider'   => [ 'Infinite Slider',     'InfiniteSlider'     ],
				'floating-elements' => [ 'Floating Elements',   'FloatingElements'   ],
				'particle-bg'       => [ 'Particle Background', 'ParticleBackground' ],
				'shape-animation'   => [ 'Shape Animation',     'ShapeAnimation'     ],
			] ),

			// --- Interactive ---
			self::definitions( 'Interactive', [
				'tabs'                       => [ 'Tabs',                'Tabs'                  ],
				'accordion'                  => [ 'Accordion',           'Accordion'             ],
				'nested-accordion'           => [ 'Nested Accordion',    'NestedAccordion'       ],
				'nested-tabs'                => [ 'Nested Tabs',         'NestedTabs'            ],
				'toggle'                     => [ 'Toggle',              'Toggle'                ],
				'modal'                      => [ 'Modal',               'Modal'                 ],
				'popup'                      => [ 'Popup',               'Popup'                 ],
				'off-canvas'                 => [ 'Off-Canvas',          'OffCanvas'             ],
				'tooltip'                    => [ 'Tooltip',             'Tooltip'               ],
				'hotspot'                    => [ 'Hotspot',             'Hotspot'               ],
				'interactive-cards'          => [ 'Interactive Cards',   'InteractiveCards'      ],
				'flip-box'                   => [ 'Flip Box',            'FlipBox'               ],
				'content-switcher'           => [ 'Content Switcher',    'ContentSwitcher'       ],
				'interactive-before-after'   => [ 'Before/After',        'BeforeAfter'           ],
				'comparison-slider'          => [ 'Comparison Slider',   'ComparisonSlider'      ],
				'interactive-image-accordion'=> [ 'Image Accordion',     'ImageAccordion'        ],
				'interactive-timeline'       => [ 'Interactive Timeline','InteractiveTimeline'   ],
				'stepper'                    => [ 'Stepper',             'Stepper'               ],
				'faq'                        => [ 'FAQ',                 'Faq'                   ],
				'faq-search'                 => [ 'FAQ Search',          'FaqSearch'             ],
			] ),

			// --- Data Visualization ---
			self::definitions( 'DataViz', [
				'dataviz-progress-bar' => [ 'Progress Bar',       'ProgressBar'       ],
				'circular-progress'    => [ 'Circular Progress',  'CircularProgress'  ],
				'dataviz-counter'      => [ 'Counter',            'Counter'           ],
				'dataviz-statistics'   => [ 'Statistics',         'Statistics'        ],
				'bar-chart'            => [ 'Bar Chart',          'BarChart'          ],
				'line-chart'           => [ 'Line Chart',         'LineChart'         ],
				'pie-chart'            => [ 'Pie Chart',          'PieChart'          ],
				'donut-chart'          => [ 'Donut Chart',        'DonutChart'        ],
				'area-chart'           => [ 'Area Chart',         'AreaChart'         ],
				'radar-chart'          => [ 'Radar Chart',        'RadarChart'        ],
				'data-table'           => [ 'Data Table',         'DataTable'         ],
				'dataviz-comparison'   => [ 'Comparison Table',   'ComparisonTable'   ],
				'pricing-comparison'   => [ 'Pricing Comparison', 'PricingComparison' ],
				'dynamic-table'        => [ 'Dynamic Table',      'DynamicTable'      ],
				'kpi-cards'            => [ 'KPI Cards',          'KpiCards'          ],
			] ),

			// --- Maps ---
			self::definitions( 'Data', [
				'google-map'           => [ 'Google Map',         'GoogleMap'         ],
				'openstreet-map-widget'=> [ 'OpenStreetMap',      'OpenStreetMap'     ],
				'leaflet-map'          => [ 'Leaflet Map',        'LeafletMap'        ],
				'mapbox'               => [ 'Mapbox',             'Mapbox'            ],
				'multi-location-map'   => [ 'Multiple Locations', 'MultiLocationMap'  ],
				'map-store-locator'    => [ 'Store Locator',      'StoreLocator'      ],
				'location-finder'      => [ 'Location Finder',    'LocationFinder'    ],
				'interactive-map'      => [ 'Interactive Map',    'InteractiveMap'    ],
				'map-marker'           => [ 'Map Marker',         'MapMarker'         ],
				'route-map'            => [ 'Route Map',          'RouteMap'          ],
				'contact-map'          => [ 'Contact Map',        'ContactMap'        ],
			] ),

			// --- Video / Audio ---
			self::definitions( 'Media', [
				'video'           => [ 'Video',            'Video'           ],
				'video-gallery'   => [ 'Video Gallery',    'VideoGallery'    ],
				'video-carousel'  => [ 'Video Carousel',   'VideoCarousel'   ],
				'youtube-video'   => [ 'YouTube Video',    'YouTubeVideo'    ],
				'vimeo-video'     => [ 'Vimeo Video',      'VimeoVideo'      ],
				'video-popup'     => [ 'Video Popup',      'VideoPopup'      ],
				'video-background'=> [ 'Video Background', 'VideoBackground' ],
				'video-playlist'  => [ 'Video Playlist',   'VideoPlaylist'   ],
				'video-lightbox'  => [ 'Video Lightbox',   'VideoLightbox'   ],
				'audio-player'    => [ 'Audio Player',     'AudioPlayer'     ],
				'podcast-player'  => [ 'Podcast Player',   'PodcastPlayer'   ],
				'spotify-embed'   => [ 'Spotify Embed',    'SpotifyEmbed'    ],
				'soundcloud-embed'=> [ 'SoundCloud Embed', 'SoundCloudEmbed' ],
				'youtube-playlist'=> [ 'YouTube Playlist', 'YouTubePlaylist' ],
			] ),

			// --- FAQ / Documentation ---
			self::definitions( 'FAQ', [
				'faq-widget'       => [ 'FAQ',                      'Faq'           ],
				'faq-accordion'    => [ 'FAQ Accordion',            'FaqAccordion'  ],
				'faq-search-widget'=> [ 'FAQ Search',               'FaqSearch'     ],
				'docs-nav'         => [ 'Documentation Navigation', 'DocsNav'       ],
				'docs-toc'         => [ 'Documentation TOC',        'DocsToc'       ],
				'knowledge-base'   => [ 'Knowledge Base',           'KnowledgeBase' ],
				'glossary'         => [ 'Glossary',                 'Glossary'      ],
				'term-tooltip'     => [ 'Term Tooltip',             'TermTooltip'   ],
				'changelog'        => [ 'Changelog',                'Changelog'     ],
				'docs-cards'       => [ 'Documentation Cards',      'DocsCards'     ],
			] ),

			// --- User / Login ---
			self::definitions( 'User', [
				'user-login'         => [ 'Login',          'Login'         ],
				'user-register'      => [ 'Register',       'Register'      ],
				'user-profile'       => [ 'User Profile',   'UserProfile'   ],
				'user-avatar'        => [ 'User Avatar',    'UserAvatar'    ],
				'user-logout'        => [ 'Logout',         'Logout'        ],
				'user-password-reset'=> [ 'Password Reset', 'PasswordReset' ],
				'user-dashboard'     => [ 'User Dashboard', 'UserDashboard' ],
				'user-account-menu'  => [ 'Account Menu',   'AccountMenu'   ],
				'user-greeting'      => [ 'User Greeting',  'UserGreeting'  ],
				'login-popup'        => [ 'Login Popup',    'LoginPopup'    ],
				'social-login'       => [ 'Social Login',   'SocialLogin'   ],
			] ),

			// --- Dynamic WordPress ---
			self::definitions( 'Dynamic', [
				'dynamic-field'         => [ 'Dynamic Field',         'DynamicField'         ],
				'dynamic-posts'         => [ 'Dynamic Posts',         'DynamicPosts'         ],
				'dynamic-pages'         => [ 'Dynamic Pages',         'DynamicPages'         ],
				'dynamic-categories'    => [ 'Dynamic Categories',    'DynamicCategories'    ],
				'dynamic-tags'          => [ 'Dynamic Tags',          'DynamicTags'          ],
				'dynamic-cpt'           => [ 'Dynamic CPT',           'DynamicCpt'           ],
				'dynamic-taxonomies'    => [ 'Dynamic Taxonomies',    'DynamicTaxonomies'    ],
				'custom-fields'         => [ 'Custom Fields',         'CustomFields'         ],
				'dynamic-images'        => [ 'Dynamic Images',        'DynamicImages'        ],
				'dynamic-urls'          => [ 'Dynamic URLs',          'DynamicUrls'          ],
				'dynamic-titles'        => [ 'Dynamic Titles',        'DynamicTitles'        ],
				'dynamic-excerpts'      => [ 'Dynamic Excerpts',      'DynamicExcerpts'      ],
				'dynamic-author'        => [ 'Dynamic Author',        'DynamicAuthor'        ],
				'dynamic-date'          => [ 'Dynamic Date',          'DynamicDate'          ],
				'dynamic-terms'         => [ 'Dynamic Terms',         'DynamicTerms'         ],
				'dynamic-relationships' => [ 'Dynamic Relationships', 'DynamicRelationships' ],
				'query-builder'         => [ 'Query Builder',         'QueryBuilder'         ],
				'custom-query'          => [ 'Custom Query',          'CustomQuery'          ],
				'ajax-query'            => [ 'AJAX Query',            'AjaxQuery'            ],
				'rest-api-data'         => [ 'REST API Data',         'RestApiData'          ],
			] ),

			// --- ACF / CPT ---
			self::definitions( 'ACF', [
				'acf-text'        => [ 'ACF Text',              'AcfText'        ],
				'acf-image'       => [ 'ACF Image',             'AcfImage'       ],
				'acf-gallery'     => [ 'ACF Gallery',           'AcfGallery'     ],
				'acf-url'         => [ 'ACF URL',               'AcfUrl'         ],
				'acf-link'        => [ 'ACF Link',              'AcfLink'        ],
				'acf-repeater'    => [ 'ACF Repeater',          'AcfRepeater'    ],
				'acf-group'       => [ 'ACF Group',             'AcfGroup'       ],
				'acf-relationship'=> [ 'ACF Relationship',      'AcfRelationship'],
				'acf-flexible'    => [ 'ACF Flexible Content',  'AcfFlexible'    ],
			] ),

			// --- Developer ---
			self::definitions( 'Developer', [
				'code-block'        => [ 'Code Block',          'CodeBlock'        ],
				'syntax-highlighter'=> [ 'Syntax Highlighter',  'SyntaxHighlighter'],
				'code-copy'         => [ 'Code Copy Button',    'CodeCopy'         ],
				'terminal'          => [ 'Terminal',            'Terminal'         ],
				'json-viewer'       => [ 'JSON Viewer',         'JsonViewer'       ],
				'api-viewer'        => [ 'API Response Viewer', 'ApiViewer'        ],
				'html-preview'      => [ 'HTML Preview',        'HtmlPreview'      ],
				'css-preview'       => [ 'CSS Preview',         'CssPreview'       ],
				'js-preview'        => [ 'JavaScript Preview',  'JsPreview'        ],
				'rest-viewer'       => [ 'REST API Viewer',     'RestViewer'       ],
				'dynamic-json'      => [ 'Dynamic JSON',        'DynamicJson'      ],
			] ),

			// --- AI ---
			self::definitions( 'AI', [
				'ai-text-generator'    => [ 'AI Text Generator',    'TextGenerator'    ],
				'ai-content-writer'    => [ 'AI Content Writer',    'ContentWriter'    ],
				'ai-faq-generator'     => [ 'AI FAQ Generator',     'FaqGenerator'     ],
				'ai-product-description'=> ['AI Product Description','ProductDescription'],
				'ai-blog-generator'    => [ 'AI Blog Generator',    'BlogGenerator'    ],
				'ai-image-generator'   => [ 'AI Image Generator',   'ImageGenerator'   ],
				'ai-chatbot'           => [ 'AI Chatbot',           'Chatbot'          ],
				'ai-search'            => [ 'AI Search',            'Search'           ],
				'ai-recommendations'   => [ 'AI Recommendations',   'Recommendations'  ],
				'ai-form-assistant'    => [ 'AI Form Assistant',    'FormAssistant'    ],
				'ai-translation'       => [ 'AI Translation',       'Translation'      ],
				'ai-summarizer'        => [ 'AI Summarizer',        'Summarizer'       ],
				'ai-content-improver'  => [ 'AI Content Improver',  'ContentImprover'  ],
			] ),

			// --- Premium Creative UI ---
			self::definitions( 'Creative', [
				'bento-grid'            => [ 'Bento Grid',                'BentoGrid'            ],
				'adv-image-accordion'   => [ 'Advanced Image Accordion',  'AdvImageAccordion'    ],
				'3d-image-cards'        => [ '3D Image Cards',            'ImageCards3D'         ],
				'3d-product-cards'      => [ '3D Product Cards',          'ProductCards3D'       ],
				'glass-cards'           => [ 'Glassmorphism Cards',       'GlassCards'           ],
				'magnetic-buttons'      => [ 'Magnetic Buttons',          'MagneticButtons'      ],
				'liquid-buttons'        => [ 'Liquid Buttons',            'LiquidButtons'        ],
				'spotlight-cards'       => [ 'Spotlight Cards',           'SpotlightCards'       ],
				'cursor-spotlight'      => [ 'Cursor Spotlight',          'CursorSpotlight'      ],
				'interactive-gradient'  => [ 'Interactive Gradient',      'InteractiveGradient'  ],
				'noise-bg'              => [ 'Noise Background',          'NoiseBackground'      ],
				'mesh-gradient'         => [ 'Mesh Gradient',             'MeshGradient'         ],
				'animated-gradient'     => [ 'Animated Gradient',         'AnimatedGradient'     ],
				'svg-morph'             => [ 'SVG Morph',                 'SvgMorph'             ],
				'svg-draw'              => [ 'SVG Draw Animation',        'SvgDraw'              ],
				'scroll-image-seq'      => [ 'Scroll-Based Image Sequence','ScrollImageSequence' ],
				'adv-grid'              => [ 'Advanced Grid',             'AdvancedGrid'         ],
				'horizontal-scroll'     => [ 'Horizontal Scroll',         'HorizontalScroll'     ],
				'horizontal-timeline'   => [ 'Horizontal Timeline',       'HorizontalTimeline'   ],
				'vertical-timeline'     => [ 'Vertical Timeline',         'VerticalTimeline'     ],
				'sticky-sections'       => [ 'Sticky Sections',           'StickySections'       ],
				'scroll-snap'           => [ 'Scroll Snap',               'ScrollSnap'           ],
				'layered-cards'         => [ 'Layered Cards',             'LayeredCards'         ],
				'stacked-cards'         => [ 'Stacked Cards',             'StackedCards'         ],
				'overlapping-sections'  => [ 'Overlapping Sections',      'OverlappingSections'  ],
				'command-palette'       => [ 'Command Palette',           'CommandPalette'       ],
				'floating-dock'         => [ 'Floating Dock',             'FloatingDock'         ],
				'bottom-nav'            => [ 'Bottom Navigation',         'BottomNav'            ],
				'notification-center'   => [ 'Notification Center',       'NotificationCenter'   ],
				'progress-nav'          => [ 'Progress Navigation',       'ProgressNav'          ],
				'interactive-dashboard' => [ 'Interactive Dashboard',     'InteractiveDashboard' ],
				'dashboard-cards'       => [ 'Dashboard Cards',           'DashboardCards'       ],
			] )
		);
	}

	/**
	 * @return array<string, array{name: string, class: string, file: string}>
	 */
	public static function enabled() {
		$disabled = function_exists( 'get_option' ) ? get_option( 'astrax_disabled_widgets', [] ) : [];
		$disabled = is_array( $disabled ) ? $disabled : [];

		return array_diff_key( self::all(), array_flip( $disabled ) );
	}

	/**
	 * @param string                                     $group
	 * @param array<string, array{0: string, 1: string}> $widgets
	 * @return array<string, array{name: string, class: string, file: string}>
	 */
	private static function definitions( $group, $widgets ) {
		$definitions = [];
		foreach ( $widgets as $slug => $widget ) {
			$path      = '' === $group ? 'Widgets/' : 'Widgets/' . $group . '/';
			$namespace = '' === $group ? '' : $group . '\\';
			$definitions[ $slug ] = [
				'name'  => $widget[0],
				'class' => __NAMESPACE__ . '\\' . $namespace . $widget[1],
				'file'  => $path . $widget[1] . '.php',
			];
		}
		return $definitions;
	}
}
